---

version: '3'

services:

    db:
        image: postgres:latest
        environment:
            POSTGRES_USER: postgres_user
            POSTGRES_PASSWORD: postgres_password
            POSTGRES_DB: postgres_db
        ports:
            - "5430:5432"
        volumes:
            - ./pgdata:/var/lib/postgresql/data

    web:
        build:
            context: .
        command: make start
        ports:
            - "8000:8000"
        # env_file: '.env'
        volumes:
            # - "web_static:/web/priv/static"
            - ".:/app"
            # - "~/.bash_history:/root/.bash_history:cached"
            # - ".bashrc:/root/.bashrc:cached"
            - "/tmp:/tmp"
        depends_on:
            - db

volumes:
    pgdata:
    # web_node_modules:
    # web_static:
    # app_build:
    # app_deps:
